spring:
  datasource:
    url: jdbc:mysql://localhost:3306/globox
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yaser
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update