package com.globox.ali.service;

import com.globox.ali.entities.VWDirectorsWritersSameAndAliveWithNoPresentBirthDayEntity;
import com.globox.ali.repository.VWDirectorsWritersSameAndAliveWithNoPresentBirthDayRepositoryImpl;
import org.springframework.stereotype.Service;

@Service
public class VWDirectorsWritersSameAndAliveWithNoPresentBirthDayServiceImpl
        extends BaseAbstractService<VWDirectorsWritersSameAndAliveWithNoPresentBirthDayEntity, String, VWDirectorsWritersSameAndAliveWithNoPresentBirthDayRepositoryImpl> {
}