package com.globox.ali.service;

import com.globox.ali.dto.VWDirectorsWritersSameAndAliveWithNoPresentBirthDayDto;
import com.globox.ali.entities.VWDirectorsWritersSameAndAliveWithNoPresentBirthDayEntity;
import com.globox.ali.repository.VWDirectorsWritersSameAndAliveWithNoPresentBirthDayRepositoryImplI;
import org.springframework.stereotype.Service;

@Service
public class VWDirectorsWritersSameAndAliveWithNoPresentBirthDayService
        extends BaseImmutableAbstractService<VWDirectorsWritersSameAndAliveWithNoPresentBirthDayEntity, VWDirectorsWritersSameAndAliveWithNoPresentBirthDayDto, String, VWDirectorsWritersSameAndAliveWithNoPresentBirthDayRepositoryImplI> {
}